Add the other CSharp Project
narze/coffee-to-code pull request #115
Opened 2022-10-01 15:06 UTC by Skul1CrowN

coffee-to-code with csharp

2022-10-01 19:14 UTC, narze requested changes
Thanks for contribution! 
By the way you can submit only single source code file 😅 Can you remove all other files?

2022-10-01 19:15 UTC, narze commented on C#/Skul1CrowN/Program.cs
> +            input = Regex.Replace(input,"coffee","code", RegexOptions.IgnoreCase);
Only this file is ok

2022-10-02 06:17 UTC, Skul1CrowN commented on C#/Skul1CrowN/Program.cs
> +            input = Regex.Replace(input,"coffee","code", RegexOptions.IgnoreCase);
Ok, I will resubmit only that file.

2022-10-02 06:24 UTC, Skul1CrowN commented on C#/Skul1CrowN/Program.cs
> +            input = Regex.Replace(input,"coffee","code", RegexOptions.IgnoreCase);
I removed the other unnecessary files.

2022-10-02 16:45 UTC, narze approved these changes
👍🏻

2022-10-02 16:46 UTC, merged